#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [buttons] [electronics] [cat]"
		/show/usageDescription "Show buttons configuration (/user/config/buttons/buttons.cfg)"
		/show/usage "$0"
		exit 1
else
	cat /user/config/buttons/buttons.cfg
fi
