#!/bin/bash
/show/description "Install buttons as a service"

/system/install supervisor
cat <<\EOF > /etc/supervisor/conf.d/buttons.conf
[program:buttons]
command=/do/buttons/check
autostart=true
autorestart=true
stdout_logfile=/var/log/buttons.log
redirect_stderr=true
EOF
supervisorctl reread
supervisorctl update

/show/listecho "Copy config files" $OK
/system/makedir /opt/user/config/buttons
if [ -z "/boot/piget/config/pilight/buttons.cfg" ];then
	cp -v /boot/piget/config/buttons/buttons.cfg /opt/user/config/buttons/buttons.cfg
else
	cp -v /opt/piget/buttons/default/buttons.cfg /opt/user/config/buttons/buttons.cfg
fi
