#!/bin/bash
/show/description "buttons Status"
/show/listecho  "PRESS [CTRL-C] to quit" $WARN
/show/listecho "Supervisor status" $OK
supervisorctl status buttons
/show/description "buttons log" $OK
tail -f /var/log/buttons.log
