#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [gpio] [buttons] [electronics]"
	/show/usageDescription "Setup buttons to shutdown or reboot a Raspberry Pi"
	/show/usage "$0"
	exit 1
else
  /show/description "[BUTTONS] Copy poweroff and restart config" $OK
  cp /do/buttons/conf/poweroffReboot.cfg /user/config/buttons/buttons.cfg
  /show/file /user/config/buttons/buttons.cfg
  /do/buttons/restart
fi
