#!/bin/bash
if [ $# -ne 1 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [buttons] [electronics]"
		/show/usageDescription "Simulate a button with gpio utility"
		/show/usage "$0 bcmPin"
    /show/example "$0 26"
		exit 1
else
    #We need to convert bcm value to wpi
    pin=$(/system/bcmToWpi $1)

    /show/listecho "Simulate Press $1" $OK
    gpio mode $pin out
    gpio write $pin 0
    sleep 0.05
    gpio mode $pin in
    gpio mode $pin up
    gpio write $pin 1
fi
