#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [buttons] [electronics] [supervisor]"
		/show/usageDescription "Restart buttons service"
		/show/usage "$0"
		exit 1
else
    /show/listecho "[BUTTONS] Restart" $OK
    /do/buttons/stop
    /do/buttons/start
fi
