#!/bin/bash

if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [buttons] [electronics] [supervisor]"
		/show/usageDescription "Start buttons service"
		/show/usage "$0"
		exit 1
else
    /show/listecho "[BUTTONS] start " $OK
    supervisorctl start buttons
fi
