#!/bin/bash
/show/description "Removing buttons service"
supervisorctl stop buttons
/system/autoBackup /etc/supervisor/conf.d/buttons.conf
rm -vf /etc/supervisor/conf.d/buttons.conf
supervisorctl reread
supervisorctl update
